version: '3.9'

services:
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx/proxy_pass.conf:/etc/nginx/conf.d/proxy_pass.conf
      - ./data/nginx/conf:/etc/nginx/conf
      - ./data/www:/var/www/html
      - ./data/certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
